### ISSUE TITLE
Error occurred during query execution: ConnectorError(ConnectorError

### ISSUE THREAD

**Issue by kongyujian** [Errorname/prisma-multi-tenant#49]
It seems to me like the `pgbouncer=true` option is not being respected, any idea why this is the case?

![image](https://user-images.githubusercontent.com/872604/90330524-defc5000-dfdf-11ea-9523-58db09804297.png)

Not sure if anybody else is facing the same.

**Comment by Errorname** [comment]
Is the option on the management db url or on a tenant's ?

**Comment by kongyujian** [comment]
I have enabled that option for both management and tenant URLs.

Have checked the URL stored within DB too, and those maintain the `pgbouncer=true` option too.

**Comment by Errorname** [comment]
In that case, I'm not sure the issue comes from Prisma-multi-tenant, because it passes the URL as is.

Can you try using a PrismaClient instead and see if you replicate the issue?

**Comment by kongyujian** [comment]
Ok my bad, I recall largely the reason why I wanted to update prisma from 2.2.0 to 2.4.1 was because of this issue on Prisma

[https://github.com/prisma/prisma/issues/2921](https://github.com/prisma/prisma/issues/2921)

I think `pmt` on 2.4.1 should fix this

**Comment by Errorname** [comment]
Alright, I am finishing some work on pmt and will make a release soon (this evening probably)

**Comment by Errorname** [comment]
I just release pmt@**2.3.1** which includes your PR updating Prisma. Don't hesitate to re-open with you still have an issue!
